### ISSUE TITLE
Atualização de repositórios

### ISSUE THREAD

**Issue by hadamo** [ppc-choice/dev.api.ppcchoice.ufes.br#46]
Mudar nomes dos atributos importados para seguir o padrão 
nomeAtributo + entidadeOrigem (Usando sempre o bom senso).

Ex.: 
- Atributo **abreviatura** importado do Departamento em Disciplina:
**abreviaturaDepto**
- Atributo **nome** importada da IES na Unidade de Ensino:
  **nomeIes**

@WellersonPrenholato @hadamo @GabrielMotaBLima @guilhermegoncalvess

**Comment by Elyabe** [comment]
Ok.
