### ISSUE TITLE
Mudar nomes dos atributos importados para seguir o padrão nomeAtributo + entidadeOrigem.

### ISSUE THREAD

**Issue by guilhermegoncalvess** [ppc-choice/dev.api.ppcchoice.ufes.br#49]
Alterações nos repositories no controller de dependencia, bem como na documentação em sua documentação.

**Comment by guilhermegoncalvess** [comment]
Alterações nos repositories no controller de dependencia, bem como na documentação em sua documentação.

**Comment by Elyabe** [comment]
Ok.
